---
name: Marpa
version: 0.001_030
author:
  - Jeffrey Kegler
abstract: Generate Parsers from any BNF grammar
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Scalar::Util: 0
build_requires:
  Test::More: 0
provides:
  Marpa::UrHTML:
    file: lib/Marpa/UrHTML.pm
    version: 0.001_030
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
distribution_type: module
no_index:
  directory:
    - inc
    - t
    - author.t
    - save
    - lib/Marpa/Doc/Not_Updated
  namespace:
    - Marpa::Internal
    - Marpa::MDL::Internal
    - Marpa::MDLex::Internal
    - Marpa::UrHTML::Internal
    - Marpa::Display::Internal
  package:
    - Marpa::Recognizer
    - Marpa::Evaluator
    - Marpa::Grammar
    - Marpa::MDL
    - Marpa::MDLex
    - Marpa::Offset
    - Marpa::Display
    - Marpa::Internal
