---
abstract: 'Generate Parsers from any BNF grammar'
author:
  - 'Jeffrey Kegler'
build_requires:
  Test::More: 0.94
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Marpa
no_index:
  directory:
    - inc
    - xs
    - lib/Marpa/UrHTML
    - t
    - author.t
    - save
  namespace:
    - Marpa::Recognizer
    - Marpa::Grammar
    - Marpa::Perl
    - Marpa::Offset
    - Marpa::Test
    - Marpa::Display
    - Marpa::MDL
    - Marpa::MDLex
    - Marpa::Evaluator
    - Marpa::UrHTML
    - Marpa::Internal
  package:
    - Marpa::Perl
    - Marpa::Offset
    - Marpa::Test
    - Marpa::Display
    - Marpa::MDL
    - Marpa::MDLex
    - Marpa::Evaluator
    - Marpa::UrHTML
    - Marpa::Internal
provides:
  Marpa:
    file: lib/Marpa.pm
    version: 0.205_000
recommends:
  PPI: 1.206
  Test::More: 0.94
requires:
  HTML::Parser: 3.64
  HTML::PullParser: 3.57
  Scalar::Util: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jeffreykegler/Marpa.git
version: 0.205_000
