---
abstract: 'Generate Parsers from any BNF grammar'
author:
  - 'Jeffrey Kegler'
build_requires:
  Test::More: 0.94
configure_requires:
  Module::Build: 0.36
distribution_type: module
generated_by: 'Module::Build version 0.3601'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Marpa
no_index:
  directory:
    - inc
    - t
    - author.t
    - save
    - lib/Marpa/Doc/Not_Updated
  namespace:
    - Marpa::Internal
    - Marpa::MDL::Internal
    - Marpa::MDLex::Internal
    - Marpa::UrHTML::Internal
    - Marpa::Display::Internal
    - Marpa::Test
  package:
    - Marpa::Grammar
    - Marpa::Recognizer
    - Marpa::Evaluator
    - Marpa::Offset
    - Marpa::Test
    - Marpa::Display
    - Marpa::MDL
    - Marpa::MDLex
    - Marpa::Internal
provides:
  Marpa:
    file: lib/Marpa.pm
    version: 0.007_003
  Marpa::UrHTML:
    file: lib/Marpa/UrHTML.pm
    version: 0.007_003
requires:
  HTML::PullParser: 3.57
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/jeffreykegler/Marpa.git
version: 0.007_003
