all: proof.pdf ah2002_notes.pdf ah_to_leo.pdf

proof.pdf: proof.lyx
	lyx --export pdf proof.lyx

ah2002_notes.pdf: ah2002_notes.lyx
	lyx --export pdf ah2002_notes.lyx

ah_to_leo.pdf: ah_to_leo.lyx
	lyx --export pdf ah_to_leo.lyx
